resources:
  repositories:
  - repository: Postman_test
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm custom
    inputs:
      command: custom
      verbose: false
      customCommand: install -g newman
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: newman run $(Build.SourcesDirectory)C:\Users\tamas.vojnovics\OneDrive - Accenture\Desktop\Postman_test.SimpleBooks.postman_collection -x -r junit --reporter-junit-export $(build.artifactstagingdirectory)\Results\JunitResults.xml